version: 3.18.0.{build}
configuration: Release
platform: Any CPU
before_build:
- nuget restore
  
build:
  project: NuGetPackageExplorer.sln
  verbosity: minimal
after_build:
- ps: >-
    choco pack PackageExplorer\NugetPackageExplorer.nuspec --version 3.18

    Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
artifacts:
- path: '**\NugetPackageExplorer.*.nupkg'
deploy: off
