version: 3.20.0.{build}
configuration: Release
platform: Any CPU
before_build:
    - ps: wget https://www.nuget.org/nuget.exe -OutFile .\NuGet.exe
    - ps: .\NuGet.exe restore
build:
  project: NuGetPackageExplorer.sln
  verbosity: minimal
after_build:
- ps: >-
    choco pack PackageExplorer\NugetPackageExplorer.nuspec --version 3.20

    Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
artifacts:
- path: '**\*.nupkg'
deploy: off
