name: Azure Static Web Apps PR Validation

on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy_job:
    env:
      DIST_PATH: artifacts/publish/NuGetPackageExplorer.WinUI/release_net10.0-browserwasm/wwwroot
      API_DIST_PATH: artifacts/publish/Api/release

    if: >
      github.event_name == 'pull_request' && 
      github.event.action != 'closed' && 
      github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    container: 'unoplatform/wasm-build:5.0'
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup dotnet
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0'

      - run: |
          dotnet workload install wasm-tools wasm-tools-net9

      - run: |
          cd Uno/NuGetPackageExplorer
          dotnet publish -c Release -f net10.0-browserwasm
          cd ../Api
          dotnet publish -c Release 

      - uses: actions/upload-artifact@v4
        with:
          name: wasm-site
          path: ${{ env.DIST_PATH }}

      - uses: actions/upload-artifact@v4
        with:
          name: api
          path: ${{ env.API_DIST_PATH }}

      - name: Build And Deploy
        id: builddeploy_uno
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CI }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "${{ env.DIST_PATH }}" # App source code path
          api_location: "${{ env.API_DIST_PATH }}" # Api source code path - optional
          skip_api_build: true # Skip building api project - optional
          skip_app_build: true # Skip building app project - optional
          output_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
        env:
          skip_deploy_on_missing_secrets: true

  close_pull_request_job:
    if: >
      github.event_name == 'pull_request' && 
      github.event.action == 'closed' &&
      github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_CI }}          
          action: "close"
        env:
          skip_deploy_on_missing_secrets: true
